# -*- coding: utf-8 -*-
"""Fuel_Efficiency_deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FZQr7Qd2_EIz9M5TuRVFAk6UKKSD9O17
"""

import streamlit as st
import pandas as pd
import joblib

# Load trained model
model = joblib.load("model.pkl")

# Page configuration
st.set_page_config(
    page_title="Vehicle Fuel Efficiency Predictor",
    page_icon="🚗",
    layout="centered"
)

# Title
st.title("Vehicle Fuel Efficiency Predictor")
st.write("Enter the vehicle details below to predict its fuel efficiency.")

st.divider()

# Input fields
cylinders = st.number_input(
    "Number of Cylinders",
    min_value=1,
    max_value=16,
    value=4
)

displacement = st.number_input(
    "Engine Displacement",
    min_value=0.0,
    value=150.0
)

horsepower = st.number_input(
    "Horsepower",
    min_value=0.0,
    value=100.0
)

weight = st.number_input(
    "Vehicle Weight",
    min_value=0.0,
    value=2500.0
)

acceleration = st.number_input(
    "Acceleration",
    min_value=0.0,
    value=15.0
)

model_year = st.number_input(
    "Model Year",
    min_value=1900,
    max_value=2030,
    value=1980
)

origin = st.selectbox(
    "Origin",
    ["USA", "Europe", "Japan"]
)

# Convert origin to numerical value
origin_mapping = {
    "USA": 1,
    "Europe": 2,
    "Japan": 3
}

origin_value = origin_mapping[origin]

# Prediction button
if st.button("Predict Fuel Efficiency"):

    # Create input dataframe
    input_data = pd.DataFrame({
        "cylinders": [cylinders],
        "displacement": [displacement],
        "horsepower": [horsepower],
        "weight": [weight],
        "acceleration": [acceleration],
        "model_year": [model_year],
        "origin": [origin_value]
    })

    # Make prediction
    prediction = model.predict(input_data)

    # Display result
    st.success(
        f"Predicted Fuel Efficiency: **{prediction[0]:.2f} MPG**"
    )

    # Interpretation
    if prediction[0] >= 30:
        st.info("This vehicle has relatively high fuel efficiency.")
    elif prediction[0] >= 20:
        st.warning("This vehicle has moderate fuel efficiency.")
    else:
        st.error("This vehicle has relatively low fuel efficiency.")